Traceback (most recent call last):
  File "parDE.py", line 157, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "parDE.py", line 140, in dEvol
    collect.extend(p.map(partial_de1, per))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: Cannot take a larger sample than population when 'replace=False'
Traceback (most recent call last):
  File "parDE.py", line 157, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "parDE.py", line 140, in dEvol
    collect.extend(p.map(partial_de1, per))
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/share/rkrish11/miniconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: Cannot take a larger sample than population when 'replace=False'
